# Generated by Django 2.0.3 on 2018-04-04 13:09

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='application', max_length=200)),
                ('handle', models.CharField(blank=True, max_length=200)),
                ('version_code', models.IntegerField(blank=True)),
                ('version_name', models.CharField(blank=True, max_length=200)),
                ('icon_phash', models.IntegerField(blank=True, null=True)),
                ('app_uid', models.CharField(blank=True, max_length=200)),
                ('creator', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('serial', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('raw_parameters', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Application')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sha256', models.CharField(blank=True, max_length=200)),
                ('size', models.IntegerField(blank=True)),
                ('file', models.FileField(upload_to=core.models.path_and_rename)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Experiment')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='APKFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.File')),
            ],
            bases=('core.file',),
        ),
        migrations.CreateModel(
            name='BluetoothDump',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.File')),
            ],
            bases=('core.file',),
        ),
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.File')),
            ],
            bases=('core.file',),
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Device')),
            ],
            bases=('core.device',),
        ),
        migrations.CreateModel(
            name='PCAPFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.File')),
            ],
            bases=('core.file',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Device')),
            ],
            bases=('core.device',),
        ),
        migrations.AddField(
            model_name='session',
            name='bluetooth_dump',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BluetoothDump'),
        ),
        migrations.AddField(
            model_name='session',
            name='flow_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FlowFile'),
        ),
        migrations.AddField(
            model_name='session',
            name='pcap_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PCAPFile'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='iot_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.IoTDevice'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='smartphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Smartphone'),
        ),
        migrations.AddField(
            model_name='application',
            name='apk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.APKFile'),
        ),
    ]
